
import Footer from "./Footer/page";
import "./globals.css";
import Header from "./Header/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
